// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvzV844sT2GJ2MKSz_D_KYwIAwYpvZ0o',
    appId: '1:910470723253:web:YOUR_WEB_APP_ID',
    messagingSenderId: '910470723253',
    projectId: 'baladroz-be563',
    authDomain: 'baladroz-be563.firebaseapp.com',
    storageBucket: 'baladroz-be563.appspot.com',
    databaseURL: 'https://baladroz-be563-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACvzV844sT2GJ2MKSz_D_KYwIAwYpvZ0o',
    appId: '1:910470723253:android:65e8ccae2da4296d8ab0fc',
    messagingSenderId: '910470723253',
    projectId: 'baladroz-be563',
    storageBucket: 'baladroz-be563.appspot.com',
    databaseURL: 'https://baladroz-be563-default-rtdb.firebaseio.com',
    androidClientId: '910470723253-dgnvbp4bqp38lkqbrg28ebpgl90frh00.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvzV844sT2GJ2MKSz_D_KYwIAwYpvZ0o',
    appId: '1:910470723253:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '910470723253',
    projectId: 'baladroz-be563',
    storageBucket: 'baladroz-be563.appspot.com',
    iosBundleId: 'com.reno.baladroz',
    databaseURL: 'https://baladroz-be563-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACvzV844sT2GJ2MKSz_D_KYwIAwYpvZ0o',
    appId: '1:910470723253:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '910470723253',
    projectId: 'baladroz-be563',
    storageBucket: 'baladroz-be563.appspot.com',
    iosBundleId: 'com.reno.baladroz',
    databaseURL: 'https://baladroz-be563-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACvzV844sT2GJ2MKSz_D_KYwIAwYpvZ0o',
    appId: '1:910470723253:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '910470723253',
    projectId: 'baladroz-be563',
    authDomain: 'baladroz-be563.firebaseapp.com',
    storageBucket: 'baladroz-be563.appspot.com',
    databaseURL: 'https://baladroz-be563-default-rtdb.firebaseio.com',
  );
}